services:
  - type: web
    name: micro-jpeg-compressor
    runtime: node
    region: oregon
    plan: starter
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: microjpeg-db
          property: connectionString
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false
      - key: TESTING_STRIPE_SECRET_KEY
        sync: false
      - key: TESTING_VITE_STRIPE_PUBLIC_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: VITE_TIDIO_PUBLIC_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: REDIS_URL
        sync: false
databases:
  - name: microjpeg-db
    databaseName: microjpeg
    user: microjpeg_user
    region: oregon
    plan: free
